app:
  http:
    server:
      host: 127.0.0.1
      port: 8000

  mongodb:
    app-name: ssugt_projects
    uri: mongodb://127.0.0.1:27017
    user:
    password:
    database: ssugt_projects
    pool-size: 100

  auth:
    access-token-secret-key: secret